/**
 * @Author: jzy
 * @Date: 2017/9/19
 * @Last Modified by: jzy
 * @Last Modified time: 2017/9/19
 */
export const LOGININFO = 'LOGININFO'
export const LOGOUT = 'LOGOUT'
export const NAVLIST = 'NAVLIST'
export const ROUTERMAP = 'ROUTERMAP'
export const BUTTON_LOADING = 'BUTTON_LOADING'
export const LEAVE_REMIND = 'LEAVE_REMIND'


export const DEPT_SELECT = 'DEPT_SELECT'
export const FROM_DEPT_SELECT = 'FROM_DEPT_SELECT'
export const JOB_SELECT = 'JOB_SELECT'
export const KIND_SELECT = 'KIND_SELECT'
export const CITY_SELECT = 'CITY_SELECT'
export const JOB_STATUS_SELECT = 'JOB_STATUS_SELECT'
export const JOB_STATUS_DISABLED_SELECT = 'JOB_STATUS_DISABLED_SELECT'
export const NOTICE_STATE_SELECT = 'NOTICE_STATE_SELECT'
export const WORK_TYPE_SELECT = 'WORK_TYPE_SELECT'
export const JOB_LEVEL_SELECT = 'JOB_LEVEL_SELECT'
export const TRANSFER_OUT_SELECT = 'TRANSFER_OUT_SELECT'
export const TRANSFER_IN_SELECT = 'TRANSFER_IN_SELECT'
export const SCORE_TYPE_SELECT = 'SCORE_TYPE_SELECT'
export const CLASSIFY_SELECT = 'CLASSIFY_SELECT'
export const NOTICE_TYPE_SELECT = 'NOTICE_TYPE_SELECT'
export const PLAN_THEAD = 'PLAN_THEAD'
export const STAFF_OUT_STATUS = 'STAFF_OUT_STATUS'


export const POSTER_NAME = 'POSTER_NAME'
export const POSTER_SCALE = 'POSTER_SCALE'
export const POSTER_IMGS = 'POSTER_IMGS'
export const POSTER_RESIZE = 'POSTER_RESIZE'
export const POSTER_TEXT_ADD = 'POSTER_TEXT_ADD'
export const POSTER_EDITING_INDEX = 'POSTER_EDITING_INDEX'
export const POSTER_CHANGE_TEXT = 'POSTER_CHANGE_TEXT'
export const POSTER_DIR_SET = 'POSTER_DIR_SET'
export const POSTER_CLEAR_AREA = 'POSTER_CLEAR_AREA'
export const POSTER_ADD_HISTORY = 'POSTER_ADD_HISTORY'
export const POSTER_RESET_BY_HISTORY = 'POSTER_RESET_BY_HISTORY'
export const POSTER_HISTORY_STATE = 'POSTER_HISTORY_STATE'
export const POSTER_GET_TEMPLATE = 'POSTER_GET_TEMPLATE'
export const POSTER_UPLOAD_TEMPLATE = 'POSTER_UPLOAD_TEMPLATE'
export const POSTER_REMOVE_TEMPLATE = 'POSTER_REMOVE_TEMPLATE'
export const POSTER_GET_RECORD = 'POSTER_GET_RECORD'




